### ISSUE TITLE
Unable to change Font Color in the Role

### ISSUE THREAD

**Issue by SamHkp19** [tilfin/aws-extend-switch-roles#13]
Hi Tilfin,

First of all I would thank you for building this extension tools which make our life easier.

My queries is I tried changing the font color instead of the back ground but could not achieve can you also add that feature as well, it would be great.

Thanks Again.
Sam

**Comment by tilfin** [comment]
@SamHkp19 Thanks for using my extension.

Do you want to change the font color like a following image?
![image](https://cloud.githubusercontent.com/assets/519017/24348768/d2eb950c-1317-11e7-89d2-5b2b13be5149.png)
To support thus style must hack some css definitions for AWS Management Console. As you know the extension must be following up the changes of AWS MC.
I am sorry I could not comply with your request because I would like to make sure that the costs as little as possible.

**Comment by SamHkp19** [comment]
Hi Tilfin

Thanks for your response. 

Yea you got the font part right but I am specifying about the Switch account name(Profile) and account number.

Attached is the screen shot for your reference.
![image](https://cloud.githubusercontent.com/assets/10721146/24351160/4d70931a-1302-11e7-8211-8149de462509.png)

Thanks
Sam

**Comment by tilfin** [comment]
I understand your query but it is difficult for me to maintain the feature.
Applying the color you picked up to the background is not this extension feature but MC original feature.
It just passes specified color value to POST action to move switch role page.
