### ISSUE TITLE
Colors not working as described

### ISSUE THREAD

**Issue by felipe1982** [tilfin/aws-extend-switch-roles#21]
The `color` option is only changing the colour of a thin horizontal bar under the topmost aws shortcut menus. The colors of the squares in the drop down menu are all grey.

My config
```
[profile OSSSIO-test]
role_arn = arn:aws:iam::xxxxxxxxxx:role/ITOCAccountAccess
color = 00FF00
```
![2017-06-15 12_34_14-aws management console](https://user-images.githubusercontent.com/275621/27162859-0095534c-51c7-11e7-9d99-690ef04093f5.jpg)

**Comment by s3than** [comment]
I've been able to replicate this issue on Mac OS chrome version 59.0.3071.86

Using the same user profile on Linux Chromium 59.0.3071.86 works as expected

In incognito on Mac the plugin and colors work as expected.

**Comment by tilfin** [comment]
I guess that it has been caused by conflict with the features of the other extensions you use.

**Comment by s3than** [comment]
Interesting that using the same profile on a different OS doesn't affect it. Will try and narrow it down and see what I can do to resolve. Thanks

**Comment by tilfin** [comment]
@felipe1982 @s3than Is `Hide original role history` checked on your popup setting panel? If its checkbox is unchecked, try to check it to enable. Because original history items take precedence of extened items. Therefore, this may happen if you add color definitions later. `Hide original role history` could be unchecked again after switching some roles 5 times.
