### ISSUE TITLE
Remote configuration file

### ISSUE THREAD

**Issue by hb3b** [tilfin/aws-extend-switch-roles#39]
It would be great if configurations could be read from a remote source file over HTTP/S. I can a see use case where we may want to generate this source file dynamically based on data about the user.

Ex. http://fqdn/aws_accounts/?user=hb3b

Ben

**Comment by tilfin** [comment]
I'm thinking about the remote configuration delivered by AWS API Gateway or AWS S3 in subdomains of _ aws.amazon.com_ . This way is able to keep current limited target hosts.  Does anyone want this feature?

**Comment by Fitouf** [comment]
I'm actually interested by this feature.
I have lot of accounts to manage (more than 60) so i'm searching a solution to edit automatically the config file to add/remove accounts or share with my colleagues and centralize it.
Actually,  where is stored the config file with the accounts informations put in the Chrome extension

**Comment by hb3b** [comment]
@fsiegwald Until this feature is implemented, we have a script here that generates the config for us. Since we use Ansible to provision security controls into accounts, we simply re-use that file in a Python script and then copy and paste the output into the extension.

**Comment by fsiegwald** [comment]
@hb3b Yes, we also have a Python script to generate that. But now i want to generate it directly in the extension :)

**Comment by JoostSaanen** [comment]
We are also interested in this!

**Comment by Hount** [comment]
We'd be interested if the plugin could locate the config file from local storage. Then you would not have to copy paste config from version control to browser.

**Comment by DonK5hot** [comment]
Could a secret GIST be used in this case? I'm not sure if it would make auth easier.

Or, can the config file be stored in plain text somewhere? I can't find it in Chrome or Firefox (Linux). This way I could sync it with my dotfiles management software.

**Comment by sheldonhull** [comment]
@DonK5hot a secret gist is just unlisted, not truly secure. I'd be wary of putting list of accounts or even account names in something like that. I consider secret gists  public in my approach and only save content to them that I'd be willing to post on my blog or in public without any concerns. 

Perhaps just cloning repo locally and being able to point to the file locally might work. The issue is syncing among multiple people rather than just one is always security I'd think.

**Comment by adbig** [comment]
If the plugin could read the configuration from a local file would be a very very interesting feature. We create many accounts and it is very painful to ask our sysadmin to copy/paste the config each time we create an AWS account. Also, many Thanks for this plugin that already greatly improves our efficiency every day !

**Comment by tilfin** [comment]
It is difficult to read local files in background from the viewpoint of security in the transition of the specification of Chrome extension. I think it is best to read the remote file, but it is not easy to adjust the cache and acquisition timing. Therefore it can not be implemented easily.

**Comment by adbig** [comment]
OK, thanks for your response.
Since we generate our config with a lambda function and store the config file in a S3 bucket, maybe it would be possible to read it directly on S3 as you proposed in a previous message.
Thanks !

**Comment by victorfrancax1** [comment]
I logged on to Github just to upvote this issue. At my company, my team manages 100+ accounts, and when someone adds or deletes an account, every other teammate has to manually add or delete it on their browser. We thought about something like @adbig mentioned: build the file dynamically via lambda and then push it somehow to everyone's browser, with some subscription or webhook system. I am not sure about the best way to implement this "sync" function at the extension, but it would be definitely nice to have.

**Comment by tilfin** [comment]
I was thinking this specification and the design.

Ideally, it is desirable to use an extension instance with remote URL permissions for each company. Even if you set the acquisition destination URL and parameters, The one public extension cannot limit the permission of accessible URLs.

By the way, The browser extension can communicate another one (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessageExternal).

I thought the solution that the AWS Extend Switch Roles can only receive your setting via extenal message and the private extension that your company makes can send your settings to the AESR with any shared key.
FYI) about private extension https://support.google.com/chrome/a/answer/2714278?visit_id=636987926338028775-443601718&rd=1&hl=en

I really don't have much motivation to implement the remote configuration feature because I don't need this feature personally. Therefore I think that's all I can do for free.

**Comment by tilfin** [comment]
This solution is provided as External API: Config sender at the version 0.14.0.
https://github.com/tilfin/aws-extend-switch-roles#extension-api
The feature will support the configution of JSON in the future (#106).
