### ISSUE TITLE
Please restore the dropdown menu for editing the config inline

### ISSUE THREAD

**Issue by et304383** [tilfin/aws-extend-switch-roles#50]
I used xdotool and a script to edit this automatically.  This broke entirely with the latest update it seems.

**Comment by tilfin** [comment]
I will not intend to support any automation script, so please change your script.
Clicking the configuration menu, the tab page will be active. therefore I think it's not so difficult.

**Comment by tilfin** [comment]
The reason are the following problems:
- Popup UIs do not works on the popup, for example the color picker on OS X.
- It is for users who don't notice GitHub page too difficult to know how to define anything in the textarea.
- Updating popup size for each adding a option is bothersome, because its size must be fixed values.

I think that the UI stable is important too. I will not change it unless forced by the specification of the browsers.
